### ISSUE TITLE
Use workgroup default Query result location

### ISSUE THREAD

**Issue by BDeus** [sr-26/athena-express-plus#18]
Hi,
Is it possible to not enforce the S3 Bucket and use the bucket of the workgroup `Query result location` ?
I think not set [`OutputLocation`](https://github.com/sr-26/athena-express-plus/blob/master/lib/helpers.js#L13C7-L13C21) is enough.
Thanks,

**Comment by sr-26** [comment]
Hi @BDeus,
Thanks for reporting this. We've made 's3Bucket' optional and merged the changes. The updated package will be published soon. Keep an eye out for the upcoming package update, as it will incorporate these changes.

**Comment by sr-26** [comment]
Hi @BDeus,
The package has been successfully published. So closing this issue for now.
