### ISSUE TITLE
Consider moving towards or supporting the modular SDK clients

### ISSUE THREAD

**Issue by alfaproject** [sr-26/athena-express-plus#22]
For better tree-shaking it would be nice to support the modular AWS SDK v3 clients:
```ts
import { AthenaClient } from '@aws-sdk/client-athena';
import { S3Client } from '@aws-sdk/client-s3';
```

Only a subset of commands is needed for both clients so it's a waste to require all of them in our bundles

**Comment by alfaproject** [comment]
For example, see S3: https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/src/S3.ts

It extends S3Client and basically imports ALL the possible commands which increases bundle size for no reason, specially for a library like this one

**Comment by poisonborz** [comment]
Wow, I just came to complain about exactly this, and this is the only current open issue with an already merged PR, guess it's my lucky day :D Any info on when this would be released?

**Comment by sr-26** [comment]
Hi @poisonborz, The latest version with these changes has been released. Thanks!
