### ISSUE TITLE
Library dependencies are tracked as dev dependencies [BUG]

### ISSUE THREAD

**Issue by cetteup** [sr-26/athena-express-plus#26]
**Describe the bug**
lib/helpers.js imports three 3rd party dependencies, only 1 of which is tracked as a regular dependency.
https://github.com/sr-26/athena-express-plus/blob/d2b2b3918464f906b8c3e43482d6531c9704e89a/lib/helpers.js#L4-L7

`@aws-sdk/client-athena` and `@aws-sdk/client-s3` are only tracked as dev dependencies, meaning they will not be installed by running e.g.
```sh
npm ci --omit=dev
```
Thus, unless npm happens to install a compatible version for other reasons, you will get a "Cannot find module" error for either of the `@aws-sdk` packages.

**To Reproduce**
Try using the library in any package that installs dependencies without their dev dependencies.

**Expected behavior**
Library works the same as when installed with/without dev dependencies.

**Comment by sr-26** [comment]
Thanks for your contribution @cetteup :)

**Comment by cetteup** [comment]
Sure thing @sr-26. Any idea when you might release a new version with the changes? The bug is currently keeping us from updating to the most recent version due to the above-mentioned "Cannot find module" issues.

**Comment by sr-26** [comment]
@cetteup apologies for the delay, but the latest version is now published. Thanks for your patience.
