### ISSUE TITLE
Support Reuse Query feature

### ISSUE THREAD

**Issue by overflowz** [sr-26/athena-express-plus#29]
**Is your feature request related to a problem? Please describe.**
I don't have ability to reuse the same queries to avoid calling the same thing many times.

**Describe the solution you'd like**
I would like to specify at query/root level if I want to reuse the same queries or not as well as interval. 

**Describe alternatives you've considered**
None

**Additional context**
https://docs.aws.amazon.com/athena/latest/APIReference/API_ResultReuseConfiguration.html

**Comment by sr-26** [comment]
Thanks for the suggestion. I'll add this feature soon.

**Comment by overflowz** [comment]
RE: when can we expect it to be available on NPM though?

Thank you.

**Comment by sr-26** [comment]
Hey @overflowz , just wanted to let you know that the package has been updated on npm. Feel free to check out the new feature and share any feedback you might have. Thanks for your patience.
